name: PartyTP
main: com.hybris.bukkit.party.tp.PartyTP
version: 0.2
website: 
author: Hybris95
description: 
             PartyTP allows leaders to teleport their entire group
commands:
    partytp:
        description: Teleport your members to your position
        usage: /partytp